FROM docker:28-dind

RUN apk add --no-cache openssh-server curl && ssh-keygen -A
RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh

COPY deploy_key.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys

RUN printf '#!/bin/sh\n/usr/sbin/sshd\nexec dockerd-entrypoint.sh "$@"\n' > /start.sh \
    && chmod +x /start.sh

ENTRYPOINT ["/start.sh"]
