apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: minoo25/todo-api:efd839267d2ee80ea9dbc736c81413ea5c2e905e
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: todo-config
            - secretRef:
                name: todo-secret
---
apiVersion: v1
kind: Service
metadata:
  name: todo-api
  namespace: todo
spec:
  type: ClusterIP
  selector:
    app: todo-api
  ports:
    - port: 80
      targetPort: 3000
