{
 "title": "Todo API - Golden Signals",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disponibilite (up)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"todo-api\"}"
    }
   ]
  },
  {
   "title": "Trafic (requetes/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"todo-api\"}[1m]))"
    }
   ]
  },
  {
   "title": "Erreurs (taux 5xx)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"todo-api\",status_code=~\"5..\"}[1m])) / sum(rate(http_requests_total{job=\"todo-api\"}[1m]))"
    }
   ]
  },
  {
   "title": "Latence p95 (s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"todo-api\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Taches creees (total)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    { "expr": "todo_tasks_created_total" }
   ]
  }
 ]
}